wandb_version: 1

lr:
  desc: null
  value: 3.0e-05
bs:
  desc: null
  value: 4
gradient_accumulation_steps:
  desc: null
  value: 1
datapath:
  desc: null
  value: '0'
is_warmup:
  desc: null
  value: true
num_epochs:
  desc: null
  value: 20
num_warmup_steps:
  desc: null
  value: 2000
total_steps:
  desc: null
  value: 800000
p_w:
  desc: null
  value: 0.1
v_w:
  desc: null
  value: 1.0
head_w:
  desc: null
  value: 0.1
num_workers:
  desc: null
  value: 2
embeding:
  desc: null
  value: true
act:
  desc: null
  value: 'No'
data_noise:
  desc: null
  value: true
noise:
  desc: null
  value: uniform
mean:
  desc: null
  value: 0.0
std:
  desc: null
  value: 0.2
residual:
  desc: null
  value: true,norm
max_len:
  desc: null
  value: 2048
config_path:
  desc: null
  value: config.json
b1:
  desc: null
  value: 0.9
b2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 0.5
save_freq:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.9
    framework: huggingface
    huggingface_version: 4.45.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1735534826
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.9
      6: 4.45.1
      8:
      - 5
      13: linux-x86_64
