bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 40
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 50
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 60
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 70
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 80
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 90
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 100
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 110
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 120
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 130
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 140
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 150
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 160
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 170
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 180
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 190
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 200
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 210
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 220
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 230
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 240
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 250
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 260
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 270
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 280
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 290
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 300
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 310
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 320
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 330
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 340
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 350
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 360
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 370
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 380
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 390
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 400
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 410
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 420
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 430
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 440
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 450
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 460
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 470
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 480
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 490
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 500

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 40
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 50
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 60
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 70
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 80
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 90
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 100
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 110
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 120
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 130
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 140
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 150
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 160
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 170
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 180
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 190
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 200
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 210
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 220
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 230
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 240
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 250
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 260
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 270
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 280
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 290
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 300
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 310
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 320
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 330
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 340
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 350
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 360
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 370
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 380
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 390
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 400
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 410
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 420
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 430
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 440
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 450
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 460
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 470
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 480
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 490
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 500

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 40
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 50
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 60
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 70
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 80
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 90
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 100
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 110
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 120
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 130
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 140
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 150
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 160
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 170
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 180
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 190
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 200
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 210
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 220
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 230
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 240
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 250
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 260
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 270
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 280
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 290
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 300
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 310
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 320
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 330
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 340
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 350
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 360
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 370
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 380
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 390
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 400
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 410
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 420
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 430
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 440
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 450
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 460
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 470
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 480
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 490
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 500

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 40
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 50
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 60
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 70
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 80
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 90
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 100
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 110
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 120
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 130
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 140
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 150
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 160
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 170
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 180
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 190
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 200
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 210
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 220
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 230
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 240
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 250
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 260
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 270
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 280
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 290
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 300
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 310
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 320
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 330
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 340
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 350
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 360
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 370
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 380
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 390
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 400
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 410
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 420
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 430
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 440
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 450
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 460
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 470
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 480
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 490
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 500

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 40
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 50
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 60
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 70
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 80
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 90
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 100
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 110
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 120
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 130
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 140
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 150
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 160
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 170
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 180
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 190
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 200
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 210
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 220
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 230
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 240
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 250
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 260
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 270
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 280
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 290
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 300
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 310
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 320
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 330
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 340
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 350
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 360
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 370
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 380
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 390
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 400
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 410
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 420
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 430
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 440
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 450
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 460
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 470
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 480
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 490
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 500