bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 0
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 1
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 2
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 3
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 4
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 5
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 6
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 7
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 8
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 9
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 11
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 12
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 13
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 14
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 15
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 16
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 17
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 18
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 19
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 21
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 22
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 23
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 24
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 25
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 26
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 27
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 28
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 29
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 31
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 32
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 33
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 34
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 35
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 36
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 37
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 38
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 39
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/10_embd_mustCLS/state_20 5 40

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 0
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 1
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 2
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 3
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 4
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 5
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 6
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 7
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 8
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 9
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 11
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 12
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 13
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 14
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 15
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 16
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 17
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 18
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 19
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 21
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 22
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 23
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 24
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 25
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 26
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 27
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 28
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 29
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 31
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 32
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 33
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 34
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 35
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 36
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 37
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 38
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 39
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20 5 40

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 0
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 1
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 2
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 3
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 4
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 5
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 6
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 7
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 8
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 9
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 11
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 12
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 13
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 14
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 15
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 16
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 17
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 18
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 19
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 21
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 22
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 23
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 24
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 25
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 26
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 27
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 28
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 29
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 31
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 32
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 33
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 34
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 35
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 36
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 37
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 38
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 39
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer1/30_embd_mustCLS/state_20 5 40


bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 0
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 1
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 2
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 3
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 4
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 5
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 6
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 7
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 8
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 9
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 11
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 12
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 13
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 14
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 15
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 16
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 17
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 18
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 19
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 21
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 22
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 23
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 24
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 25
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 26
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 27
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 28
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 29
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 31
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 32
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 33
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 34
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 35
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 36
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 37
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 38
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 39
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer2/50_embd_mustCLS_sharegpt/state_20 5 40

bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 0
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 1
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 2
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 3
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 4
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 5
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 6
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 7
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 8
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 9
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 10
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 11
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 12
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 13
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 14
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 15
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 16
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 17
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 18
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 19
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 20
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 21
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 22
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 23
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 24
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 25
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 26
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 27
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 28
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 29
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 30
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 31
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 32
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 33
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 34
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 35
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 36
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 37
bash llavabench_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 38
bash mmvet_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 39
bash mmvet_eagle.sh /data/sangjun/ckpt/attention_score/cls/layer3/50_embd_mustCLS_sharegpt/state_20 5 40
