python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls0.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls1.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls2.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls3.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls4.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls5.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls6.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls7.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls8.jsonl    
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls9.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls10.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls11.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls12.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls13.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls14.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls15.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls16.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls17.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls18.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls19.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls20.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls21.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls22.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls23.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls24.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls25.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls26.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls27.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls28.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls29.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls30.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls31.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls32.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls33.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls34.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls35.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls36.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls37.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls38.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls39.jsonl
python new_speed2.py /data/sangjun/ckpt/attention_score/cls/layer1/20_embd_mustCLS/state_20/mmvet_cls40.jsonl   